plugins {
    id 'java'
}

base {
    archivesName = "openremote-issuer-provider"
}

configurations {
    jarLibs
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.keycloakServices
    implementation libs.keycloakServerSpi
    implementation libs.byteBuddy
    implementation libs.byteBuddyAgent
    jarLibs libs.byteBuddyAgent
    implementation libs.slf4jApi
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    compileOnly libs.autoService
    annotationProcessor libs.autoService
}

jar {
    from {
        configurations.jarLibs.collect {
            zipTree(it)
        }
    }
}

tasks.register('installDist', Copy) {
    into "${rootDir}/build/image"
    from jar.outputs
}
