plugins {
    id 'java'
}

base {
    archivesName = "openremote-self-register-configure-event-listener"
}

configurations {
    jarLibs
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.keycloakServerSpi
    implementation libs.keycloakServerSpiPrivate
    implementation libs.keycloakCore
    implementation libs.jbossLogging
}

jar {
    from {
        configurations.jarLibs.collect {
            zipTree(it)
        }
    }
}

tasks.register('installDist', Copy) {
    into "${rootDir}/build/image"
    from jar.outputs
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}
